# Generated by Django 3.0.3 on 2020-05-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AddField(
            model_name='pointimagelist',
            name='point_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.PointProducts'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_deliverystatus',
            field=models.ManyToManyField(through='order.Order', to='order.DeliveryStatus'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_product',
            field=models.ManyToManyField(through='account.Prescription', to='product.Product'),
        ),
    ]
