# Generated by Django 3.0.3 on 2020-05-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200514_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='detaile_address',
            new_name='detail_address',
        ),
    ]
