# Generated by Django 3.0.3 on 2020-05-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200514_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='road_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
