# Generated by Django 3.0.3 on 2020-05-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200514_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='agreement',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='terms',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='auth_number',
            field=models.IntegerField(verbose_name='인증 번호'),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='mobile_number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='휴대폰 번호'),
        ),
    ]
