# Generated by Django 3.0.3 on 2020-05-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200514_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='invitation_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
