# Generated by Django 3.0.3 on 2020-05-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200515_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
