# Generated by Django 3.0.5 on 2020-05-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'explanations',
            },
        ),
        migrations.CreateModel(
            name='FrequentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'frequent_questions',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrial', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=2000)),
                ('precautions', models.TextField()),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=2000)),
                ('sub_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('header_image_url', models.URLField(max_length=2000)),
                ('header_description', models.CharField(max_length=500)),
                ('day', models.CharField(max_length=30)),
                ('pill_image_url', models.URLField(max_length=2000, null=True)),
                ('pill_description', models.CharField(max_length=100, null=True)),
                ('pill_sub_description', models.CharField(max_length=100, null=True)),
                ('pill_sub_image_url', models.URLField(max_length=2000, null=True)),
                ('ingredient', models.TextField(null=True)),
                ('manual_url', models.URLField(max_length=2000, null=True)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'products_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductExplanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('sub_content', models.CharField(max_length=200)),
                ('product_content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product_explanations',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'products_reviews',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_list', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=2000)),
                ('subscription', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle', models.TextField()),
                ('title', models.TextField(null=True)),
                ('effects', models.TextField(null=True)),
                ('point', models.TextField(null=True)),
                ('video_url', models.URLField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
