# Generated by Django 3.0.6 on 2020-05-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200518_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subscribe',
            field=models.BooleanField(default=0),
        ),
    ]
