# Generated by Django 3.0.5 on 2020-05-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'homes',
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'news_types',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'notices',
            },
        ),
        migrations.CreateModel(
            name='PillyStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pilly_stories',
            },
        ),
        migrations.CreateModel(
            name='ProductHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_headers',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'question_types',
            },
        ),
        migrations.CreateModel(
            name='StoryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=2000)),
                ('content', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('pilly_story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.PillyStory')),
            ],
            options={
                'db_table': 'story_informations',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.CharField(max_length=50)),
                ('question_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.QuestionType')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='PillyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.CharField(max_length=50)),
                ('news_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.NewsType')),
            ],
            options={
                'db_table': 'pilly_news',
            },
        ),
    ]
