# Generated by Django 3.0.3 on 2020-05-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('survey_discount', models.IntegerField(default=0)),
                ('invitation_discount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'delivery_status',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('recipient_name', models.CharField(max_length=50)),
                ('recipient_mobile', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=20)),
                ('road_address', models.CharField(max_length=100)),
                ('detail_address', models.CharField(max_length=100)),
                ('messege', models.TextField()),
                ('point', models.IntegerField(default=0)),
                ('order_number', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=150)),
                ('identification', models.BooleanField(default=1)),
                ('shopping_charge', models.IntegerField(default=0)),
                ('subscription', models.BooleanField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account')),
                ('delvery_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.DeliveryStatus')),
                ('order_product', models.ManyToManyField(through='order.Cart', to='product.Product')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Payment')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
    ]
