# Generated by Django 3.0.5 on 2020-05-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200518_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shopping_charge',
        ),
    ]
