# Generated by Django 3.0.6 on 2020-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200519_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
