# Generated by Django 3.0.6 on 2020-05-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200519_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='count',
            new_name='quantity',
        ),
    ]
