# Generated by Django 3.0.6 on 2020-05-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200519_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
