# Generated by Django 3.0.6 on 2020-05-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200520_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='anonymous',
        ),
    ]
